// `#1185`：生成物家族"产物必有源"守卫的读数。
//
// 成对口径（票面验收第 1 条）：删一个数据源而**不删产物** ⇒ 红；**恢复**或**一并删** ⇒ 绿。
// 另证：家族成员全过（现有家族）、非家族件不受影响、无标记的家族成员单独报（`no-marker`）。
import { readFileSync, existsSync } from 'node:fs';
import { isGeneratedFamily, declaredSourceOf, generatedFamilyProblems } from '../editor/lib/core/generated-family.mjs';

let bad = 0;
const ok = (label, cond, extra = '') => {
	if (cond) console.log(`      ✓ ${label}`);
	else { bad++; console.log(`      ✗ ${label}${extra ? ' ⇒ ' + extra : ''}`); }
};

const MK = (src) => `:: X [script]\n// @generated by editor/compile-story.mjs（源：${src}）——手改会被覆盖\nbody\n`;

// 一、家族谓词（单一权威：5 类成员进面，别的不进）
{
	ok('谓词：15/16/17/18 进家族', ['15-tables', '16-notes-ch1', '17-rules', '18-chargen']
		.every((n) => isGeneratedFamily(`stories/x/${n}.twee`)));
	ok('谓词：00-meta 进家族', isGeneratedFamily('stories/x/00-meta.twee'));
	ok('谓词：手写件不进家族', !['stories/x/11-fixture-cards.twee', 'stories/x/passages/01-开场.md', 'src/10-core.twee']
		.some(isGeneratedFamily));
	ok('谓词：19- 之类的新序号不进（封闭集 ⇒ 扩面须有意识登记）', !isGeneratedFamily('stories/x/19-new.twee'));
}

// 二、标记解析（与 literals 门同一条正则口径）
{
	ok('标记：取到源路径', declaredSourceOf(MK('stories/x/data/tables.json')) === 'stories/x/data/tables.json');
	ok('标记：全角括号也认', declaredSourceOf('// @generated by e（源：stories/x/data/a.json）') === 'stories/x/data/a.json');
	ok('标记：无标记 ⇒ null', declaredSourceOf(':: X\n手写') === null);
}

// 三、成对两向（核心判据）
{
	const files = { 'stories/x/15-tables.twee': MK('stories/x/data/tables.json') };
	const alive = generatedFamilyProblems({ files, exists: () => true });
	ok('① 源在 ⇒ 不报（绿）', alive.length === 0, JSON.stringify(alive));
	const dead = generatedFamilyProblems({ files, exists: (p) => p !== 'stories/x/data/tables.json' });
	ok('② 源删而产物在 ⇒ 报 1 条', dead.length === 1 && dead[0].code === 'source-missing', JSON.stringify(dead));
	ok('② 报文明说两侧（产物路径 ＋ 源路径）', dead[0].path === 'stories/x/15-tables.twee' && dead[0].why.includes('stories/x/data/tables.json'), String(dead[0]?.why));
	ok('③ 一并删（产物不在面里）⇒ 绿', generatedFamilyProblems({ files: {}, exists: () => false }).length === 0);
}

// 四、无标记的家族成员单独报（不混进 source-missing）
{
	const p = generatedFamilyProblems({ files: { 'stories/x/00-meta.twee': ':: StoryTitle\nX\n' }, exists: () => true });
	ok('无标记的家族成员 ⇒ no-marker', p.length === 1 && p[0].code === 'no-marker', JSON.stringify(p));
}

// 五、非家族件不受影响（防误伤）
{
	const p = generatedFamilyProblems({ files: { 'stories/x/11-fixture-cards.twee': MK('stories/x/data/never.json') }, exists: () => false });
	ok('非家族件即便标记指向不存在的源 ⇒ 不报（本守卫只管家族）', p.length === 0, JSON.stringify(p));
}

// 六、现有真家族成员全过（票面验收第 2 条）
{
	const { allSourceFiles } = await import('../scripts/module-order.mjs');
	const fam = allSourceFiles().filter(isGeneratedFamily);
	const src = Object.fromEntries(fam.map((f) => [f, readFileSync(f, 'utf8')]));
	const p = generatedFamilyProblems({ files: src, exists: (rel) => existsSync(rel) });
	ok(`现有家族成员全过（${fam.length} 件）`, p.length === 0, JSON.stringify(p.slice(0, 3)));
	ok('现有家族成员带标记（逐件核）', fam.every((f) => declaredSourceOf(src[f]) !== null));
	ok('家族件数 ≥ 5 类（B4 后含 00-meta）', fam.length >= 5, String(fam.length));
}

console.log(bad ? `\n✗ 生成物家族守卫自证未通过（${bad} 项）` : '\n✔ 生成物家族守卫自证通过（成对两向 ／ 无标记单列 ／ 非家族不受影响 ／ 现有成员全过）');
process.exit(bad ? 1 : 0);
