// `#1588` 自证：**生成物家族谓词**（单一权威）—— 家族正则原来写死 `1[5678]` ⇒ `#1585` 的 `19-events.twee` **不在家族里**
//
// ★后果谱（票面实测）：① 删 `19-events.twee` ⇒ genNeeds **不重编**（家族没认出；靠 `missing-manifest` 兜底才红）
//   ② `dist-fresh.mjs` 把它当**源件**参与新鲜度（口径错）③ 下一个产物（`20-…`）会**再漏一次**
// ★本件判四件：谓词认得全（含 `19-`）｜★**前缀集 ≡ 生成器写出的键**（钉法 ✗ 人眼）｜**全仓无第二份副本**（防再次分家）｜
//   消费者 `genNeeds` 真认（删 `19-events.twee` ⇒ 需重编 ✓）
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFileSync } from 'node:child_process';
import { isGeneratedFamily, GENERATED_PREFIXES, EMITTED_PREFIXES, generatedFamilyProblems } from '../editor/lib/core/generated-family.mjs';
import { maskComments } from '../editor/lib/core/mask.mjs';
import { genNeeds } from '../scripts/lib/gen-needed.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
let bad = 0;
const t = (l, ok, d = '') => { if (ok) console.log(`  ✓ ${l}`); else { bad++; console.error(`  ✗ ${l}${d ? ' —— ' + d : ''}`); } };

// ── ① 谓词：认得全（★含 `19-events.twee`）＋ 非家族 ✗ 误认 ──────────────────
{
	const yes = ['stories/s/00-meta.twee', 'stories/s/15-tables.twee', 'stories/s/16-notes-a.twee',
		'stories/s/17-rules.twee', 'stories/s/18-chargen.twee', 'stories/s/19-events.twee'];
	const no = ['stories/s/12-foo.twee', 'stories/s/20-next.twee', 'stories/s/00-story.json',
		'stories/s/passages/01-a.md', 'src/10-core.twee', 'stories/s/19-events.twee.bak'];
	t('① ★`19-events.twee` 是家族成员（✗ 此前写死 `1[5678]` ⇒ 漏它 ✗）', isGeneratedFamily('stories/ev-basic/19-events.twee') === true);
	t('① 既有五类仍认（00-meta／15／16-notes／17／18）', yes.every(isGeneratedFamily), JSON.stringify(yes.map((p) => [p, isGeneratedFamily(p)])));
	t('① **能假**：非家族件 ✗ 误认（`12-foo`／`20-next`／`00-story.json`／`.md`／`src/`／`.bak`）',
		no.every((p) => !isGeneratedFamily(p)), JSON.stringify(no.filter(isGeneratedFamily)));
}

// ── ② ★钉法：`GENERATED_PREFIXES` ≡ 生成器（`emit.mjs`）**写出**的键 ──────────
{
	const src = readFileSync(join(ROOT, 'editor/lib/core/emit.mjs'), 'utf8');
	// ★按**写入面**抽：`files['15-tables.twee'] = …`（行为面：那是生成器真写出的名字）
	const literal = [...src.matchAll(/files\['([0-9]{2})-[^']*'\]\s*=/g)].map((m) => m[1]);
	// ★模板键（`16-notes-*.twee` 这类动态名）按前缀补：源里以 `files[\`16-notes` 形出现
	const tpl = [...src.matchAll(/files\[`([0-9]{2})-[^`]*`\]\s*=/g)].map((m) => m[1]);
	const actual = [...new Set([...literal, ...tpl])].sort();
	t('② ★`EMITTED_PREFIXES` ≡ 生成器**字面**写出的键（★加新产物**必须**登记 —— ✗ 靠人眼同步）',
		JSON.stringify(actual) === JSON.stringify([...EMITTED_PREFIXES].sort()),
		`生成器=${actual.join('／')}｜EMITTED=${[...EMITTED_PREFIXES].sort().join('／')}`);
	t('②b ★约定前缀（名字由数据给，✗ 生成器字面写）也在家族里：`16-notes-*.twee` ⇒ 仍被认（notes 面 ✓）',
		isGeneratedFamily('stories/s/16-notes-a.twee') && GENERATED_PREFIXES.includes('16') && !EMITTED_PREFIXES.includes('16'));
}

// ── ③ ★防副本：全仓 ✗ 许有第二份家族正则（`19-` 漏认的根因就是"又写了一份"）────
{
	const hits = [];
	for (const f of ['scripts/lib/gen-needed.mjs', 'scripts/dist-fresh.mjs', 'build.mjs', 'test/gen-needed.mjs', 'test/codex-panel.mjs', 'test/prose-vocabulary.mjs']) {
		// ★必须**剥注释**再判（✗ 否则本笔自己的说明文字里的"原写 `1[5678]`"会被判成副本 —— 本片第一版就踩了 ✓）
		const txt = maskComments(readFileSync(join(ROOT, f), 'utf8'), { file: f });
		if (/1\[5678\]|1\[5-9\]|1\[0-9\]\{1,2\}-/.test(txt)) hits.push(f);
	}
	t('③ ★**无第二份家族正则**（各消费者一律走单一权威 `isGeneratedFamily` ✓）', hits.length === 0, hits.join('／'));
}

// ── ④ 消费者：`genNeeds` 真认（删 `19-events.twee` ⇒ 需重编，✗ 靠 `missing-manifest` 兜底）──
{
	const r = genNeeds({ declared: ['stories/s/19-events.twee'], exists: (f) => f !== 'stories/s/19-events.twee', family: isGeneratedFamily, dataFiles: ['events.json'] });
	t('④ 消费者：删 `19-events.twee` ⇒ `genNeeds` 认出**需重编**（✗ 静默跳过）', r.needed.length === 1 && r.needed[0] === 'stories/s/19-events.twee', JSON.stringify(r));
	t('④ 反向：产物齐备 ＋ 无 `stale` ⇒ 仍跳过（幂等不变 ✓）',
		genNeeds({ declared: ['stories/s/19-events.twee'], exists: () => true, family: isGeneratedFamily, dataFiles: ['events.json'] }).needed.length === 0);
}

// ── ⑤ 顺带：家族模块的**守卫**两格（该模块此前无判据件 ⇒ 一并给覆盖面）──────────
{
	const fp = (files, exists) => generatedFamilyProblems({ files, exists });
	t('⑤ `source-missing`：标记载明的源不在磁盘 ⇒ 点名',
		fp({ 'stories/s/15-tables.twee': '// @generated by x（源：stories/s/data/tables.json）' }, () => false).some((p) => p.code === 'source-missing'));
	t('⑤ `no-marker`：家族成员没有 `@generated` 标记 ⇒ 点名（看不出源 ⇒ 无从核源）',
		fp({ 'stories/s/19-events.twee': ':: seg [script]\nwindow.x = 1;' }, () => true).some((p) => p.code === 'no-marker'));
}

if (bad) { console.error(`\n✗ 生成物家族谓词自证失败 ${bad} 项`); process.exit(1); }
console.log('\n✔ 生成物家族谓词自证通过（含 `19-events`｜前缀集 ≡ 生成器｜无副本｜genNeeds 真认）');
