// 故事编译器（`#762` P0 · 伞 `#761` 的 D2）：**故事 JSON 包 ⇒ twee**
//
// 谁是源、谁是产物：
//   `stories/<slug>/data/*.json` 是**源**；生成的 twee 是**产物**（带 `@generated` 标记 ⇒ K4 判据）。
// 本文件是 P0 的最小实现：只生成**声明面**（`Game Tables`）与**接入契约**（`StoryBindings`）两段；
//   条件表（`17-rules.twee`）与散文段落留到下一步（设计稿 §3 的边界：结构进 JSON、文本留文本）。
//
// 用法：
//   node editor/compile-story.mjs <slug> [--out=<dir>]     # 默认写到 build/generated/<slug>/
//   幂等：同一份 data/ 连跑两次，产物逐字节相同（P0 验收判据之一）。
//
// 为什么先做这件事：UI 不是难点，**schema 立不立得住**才是。本编译器就是那个证伪点——
//   它若能把手写版**逐 token 复现**（`editor/equiv.mjs` 的 L1/L3），数据化这条路就走得通。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

/** 查表表达式的两种形状：普通取键 / 可选链取键（接缝路径如 `Sg.story.mechanics()` 用后者）。 */
const access = (from, key, optional) => {
	// `from` 已经是全局根（`window.` / `Sg.`）时**原样用**——手写版两种写法都有（`window.Sg.story.mechanics()` 与 `Sg.story.mechanics()`），
	// schema 得能表达"哪个根"，否则生成物与手写版差一个前缀（L3 报差异时要人肉分辨，不值当）。
	const base = /^(window\.|Sg\.)/.test(from) ? from : `window.${from}`;
	return optional ? `${base}?.[${key}]` : `${base}[${key}]`;
};

/** 契约成员的 `kind` → JS 表达式（**封闭集合**；新增 kind 必须同时改这里、`--selftest` 与设计稿 §2.3）。
 *
 *  v0 六个 ＋ v1 四个（`#762` 车道 A 实测缺口：故事 1/2 的真实契约都用得上，且都**不需要** `kind:'js'` 逃生舱）：
 *   · `lookup`        ｜ `{ from, key, default, optional?, required?, error? }` —— 查表；`required` 表达契约的 fail-loud
 *   · `lookup-field`  ｜ 在 `lookup` 基础上取一个字段，并可给兜底表达式（如 `String(key)`）
 *   · `bool-exists`   ｜ `{ path }` ⇒ `!!window.<path>`（"这张故事表在不在"）
 *   · `state-ref`     ｜ `{ path, default, arg? }` ⇒ `<arg>?.<path> ?? <default>`（如 `foeState(pc)` 读 `pc.dragon`）
 */
export const KINDS = {
	'empty-object': () => '() => ({})',
	'empty-array': () => '() => []',
	'null': () => '() => null',
	'const': (m) => `() => ${jsLiteral(m.value)}`,
	'game-ref': (m) => `() => window.${m.path}`,
	'identity-string': () => '(id) => String(id)',
	'lookup': (m) => {
		const k = m.key ?? 'id';
		const value = access(m.from, k, m.optional !== false);
		if (!m.required) return `(${k}) => ${value} ?? ${jsLiteral(m.default ?? null)}`;
		const msg = String(m.error ?? `Sg.story.${m.name}：${k} 未登记（结构缺失必须报错，#441-E）`).replaceAll('{key}', '${' + k + '}');
		return `(${k}) => {\n\t\tconst v = ${value};\n\t\tif (!v) throw new Error(\`${msg}\`);\n\t\treturn v;\n\t}`;
	},
	'lookup-field': (m) => {
		const k = m.key ?? 'id';
		const value = access(m.from, k, m.optional !== false);
		const field = m.field ? `?.${m.field}` : '';
		return `(${k}) => ${value}${field} ?? ${m.fallback ?? 'null'}`;
	},
	'bool-exists': (m) => `() => !!window.${m.path}`,
	'state-ref': (m) => {
		const a = m.arg ?? 'pc';
		return `(${a}) => ${a}?.${m.path} ?? ${jsLiteral(m.default ?? {})}`;
	},
};

/** 纯函数：JS 字符串字面量 —— 一律**单引号**（与仓内既有代码同风格；L3 要剥空白后逐字节相同）。 */
export const jsString = (v) => `'${String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;

const jsLiteral = (v) => literal(v, 0);

/** 纯函数：对象键 —— 合法标识符用裸键，其余用单引号串。 */
export const jsKey = (k) => (/^[A-Za-z_$][\w$]*$/.test(k) ? k : jsString(k));

/** 纯函数：JSON 值 → 带 tab 缩进的 JS 字面量（空表/空对象写成一行，便于人读）。 */
export const literal = (v, ind = 0) => {
	const pad = '\t'.repeat(ind);
	if (Array.isArray(v)) {
		if (!v.length) return '[]';
		return `[\n${v.map((x) => `${pad}\t${literal(x, ind + 1)}`).join(',\n')}\n${pad}]`;
	}
	if (v && typeof v === 'object') {
		const keys = Object.keys(v);
		if (!keys.length) return '{}';
		return `{\n${keys.map((k) => `${pad}\t${jsKey(k)}: ${literal(v[k], ind + 1)}`).join(',\n')}\n${pad}}`;
	}
	return typeof v === 'string' ? jsString(v) : String(v);
};

/** 纯函数：`data/tables.json` → `Game Tables` 段（不含段头与生成标记）。 */
export const emitTables = (d) => {
	const one = 'window.Game = Object.assign(window.Game ?? {}, ' + literal(d.containers) + ');';
	const merges = (d.merges ?? []).map((m) => {
		const segs = m.target.split('.');
		const leaf = segs.pop();
		const init = literal(m.default);
		const body = Object.entries(m.value).map(([k, v]) => `\t${jsKey(k)}: ${jsString(v)},`).join('\n');
		return `Object.assign(((window.${segs.join('.')} ??= ${init}).${leaf}), {\n${body}\n});`;
	});
	return [one, ...merges].join('\n');
};

/** 纯函数：`data/contract.json` → `StoryBindings` 段（不含段头与生成标记）。 */
export const emitContract = (d) => {
	const rows = d.members.map((m) => {
		const fn = KINDS[m.kind];
		if (!fn) throw new Error(`未知的契约 kind：${m.kind}（成员 ${m.name}）——新增 kind 必须同时改 KINDS 与设计稿 §2.3`);
		return `\t${m.name}: ${fn(m)},`;
	});
	return ['window.Sg ??= {};', `Object.assign((window.Sg.story ??= {}), {\n${rows.join('\n')}\n});`].join('\n');
};

const GENERATED = (src) => `// @generated by editor/compile-story.mjs（源：${src}）——**手改会在下次编译被覆盖**（#762 / K4）`;

/** 纯函数：把两段拼成一份 twee（＝现在的 `15-tables.twee` 形状）。 */
export const compile = ({ tables, contract, slug }) => {
	const parts = [];
	parts.push(`:: ${tables.section} [script]`);
	parts.push(GENERATED(`stories/${slug}/data/tables.json`));
	if (tables.note) parts.push(`// ${tables.note}`);
	parts.push(emitTables(tables));
	parts.push('');
	parts.push(`:: ${contract.section} [script]`);
	parts.push(GENERATED(`stories/${slug}/data/contract.json`));
	if (contract.note) parts.push(`// ${contract.note}`);
	parts.push(emitContract(contract));
	parts.push('');
	return parts.join('\n');
};

const selftest = () => {
	let bad = 0;
	const t = (label, ok, got = '') => { if (!ok) bad++; console.log(`${ok ? '✓' : '✗'} 自证·${label}${ok ? '' : `\n    实得：${got}`}`); };
	const one = (m) => emitContract({ members: [{ name: m.name ?? 'x', ...m }] });
	const has = (m, needle) => { const got = one(m); return [got.includes(needle), got]; };
	t('lookup：默认可选链 ＋ 兜底 null', ...has({ kind: 'lookup', from: 'Game.Checks.sites', key: 'name' }, 'window.Game.Checks.sites?.[name] ?? null'));
	t('lookup：`Sg.` 根原样保留（不重复加 window.）', ...has({ kind: 'lookup', from: 'Sg.story.mechanics()?.pools', key: 'id', default: [] }, 'Sg.story.mechanics()?.pools?.[id] ?? []'));
	t('lookup：`optional:false` ⇒ 普通取键', ...has({ kind: 'lookup', from: 'Game.Notes.entries', key: 'k', optional: false }, 'window.Game.Notes.entries[k] ??'));
	t('lookup：`required:true` ⇒ 显式抛错（契约 fail-loud）', ...has({ kind: 'lookup', from: 'Game.Checks.sites', key: 'name', required: true, name: 'checkSite', error: 'Sg.story.checkSite：位点「{key}」未登记（结构缺失必须报错，#441-E）' }, 'throw new Error(`Sg.story.checkSite：位点「${name}」未登记'));
	t('lookup-field：取字段 ＋ 兜底表达式', ...has({ kind: 'lookup-field', from: 'Sg.story.mechanics()?.actions', key: 'id', field: 'label', fallback: 'String(id)' }, 'Sg.story.mechanics()?.actions?.[id]?.label ?? String(id)'));
	t('bool-exists：`!!window.<path>`', ...has({ kind: 'bool-exists', path: 'Game.Chargen' }, '() => !!window.Game.Chargen'));
	t('state-ref：`<arg>?.<path> ?? default`', ...has({ kind: 'state-ref', path: 'dragon', default: {} }, '(pc) => pc?.dragon ?? {}'));
	t('未知 kind ⇒ 报错（不许静默产出半个函数）', (() => { try { one({ kind: 'nope' }); return false; } catch { return true; } })());
	if (bad) { console.error(`\n✗ 自证失败 ${bad} 项`); process.exit(1); }
	console.log('\n✔ 自证通过（8 例：lookup 四形态 · lookup-field · bool-exists · state-ref · 未知 kind 报错）');
};

if (process.argv.includes('--selftest')) { selftest(); process.exit(0); }

const main = () => {
	const slug = process.argv[2];
	if (!slug) { console.error('用法：node editor/compile-story.mjs <slug> [--out=<dir>]'); process.exit(2); }
	const outArg = process.argv.find((a) => a.startsWith('--out='));
	const OUT = outArg ? outArg.slice('--out='.length) : join(ROOT, 'build/generated', slug);
	const read = (f) => JSON.parse(readFileSync(join(ROOT, 'stories', slug, 'data', f), 'utf8'));
	const tables = read('tables.json');
	const contract = read('contract.json');
	const text = compile({ tables, contract, slug });
	mkdirSync(dirname(join(OUT, 'x')), { recursive: true });
	const dest = join(OUT, '15-tables.twee');
	writeFileSync(dest, text, 'utf8');
	console.log(`✔ ${slug}：由 data/ 生成 → ${dest.replace(ROOT, '')}（${text.length} 字节，${text.split('\n').length - 1} 行）`);
};

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main();
