// 等价判据（`#762` P0 · 设计稿 §4 的 L1/L3 实现）：**手写版 ↔ 数据版**必须等价。
//
// 一条命令跑完全部 P0 验收（自包含：**自己跑编译器**，不依赖别人先编译好，避免判一份陈旧产物）：
//   · **幂等**：同一份 data/ 连编译两次 ⇒ 产物逐字节相同；
//   · **L1 结构/行为等价**：两份 `[script]` 段各自在 `vm` 里跑一遍（同一份空白 `window`），比对
//     ① 数据容器（`window.Game`）深度相等 ② 接入契约**逐个成员 × 多组实参**的调用结果相等
//     （函数不能直接比 ⇒ 比行为；实参表**由故事自己声明的 id 驱动** ⇒ 吃参成员不再只验零参）；
//   · **L3 形式等价**：**按词法遮蔽注释**（`scripts/audit/lib/mask.mjs`，与全仓同一把刀）后，
//     剥空白与冗余尾逗号，两段逐字节相同；
//   · **面不为空**（`#557` 口径）：容器键数/叶子数/契约成员数/探针次数/归一字节数任一为 0 ⇒ **判红**
//     —— 否则"等价"这两个字没有任何证据力（只证明了"两份空东西一样空"）。
//
// 为什么注释遮蔽必须走 `maskComments` 而不是自己写正则：字符串里的 `//`（如 URL）会被正则吃掉 ⇒
//   只要差异**只**落在这种字符串里，L3 就**假绿**（实测：`'https://a.example/x'` 与
//   `'https://b.example/y'` 归一后相同）。`mask.mjs` 是单扫描器按词法遮蔽、**不动字符串内容**。
//
// 用法：node editor/equiv.mjs <slug> [--hand=<path>] [--gen=<path>]
import { readFileSync, readdirSync, existsSync } from 'node:fs';
// `#794` 第 3 步 ②：跑子进程是**宿主能力** ⇒ 经 `lib/host/proc.mjs`（core 不得 import 这一层 ✓；K6 判据③在盯 ✓）。
import { runNode } from './lib/host/proc.mjs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';
import { maskComments } from '../scripts/audit/lib/mask.mjs';
// `#794` `equiv` 弧第 1 票：**纯助手**已搬进 `editor/lib/core/probe.mjs`（逐字 ✓）
// ⇒ 本文件只 **import ＋ 转出**（老调用方与自证都不用改 ✓）。
import { L3_MODES, declaredIds, probeArgs, call, diffContract, walk, snapshot } from './lib/core/probe.mjs';
export { L3_MODES, declaredIds, probeArgs, call, diffContract, walk, snapshot };
// `#794` 弧第 2 票：碰 vm 的三个（`sandboxOf`／`runScript`／`evalSide`）搬进 `lib/host/probe.mjs`（逐字 ✓）
// ⇒ 本文件只 import ＋ 转出（老调用方与自证不改 ✓）；下一票再搬命令体 ✓。
import { sandboxOf, runScript, evalSide } from './lib/host/probe.mjs';
export { sandboxOf, runScript, evalSide };

// `#794` 抽取：纯文本助手归 **core**（浏览器安全），引擎常量前缀归 **host**。
// 为什么必须搬：原先 `equiv` 与 `extract-story` **互相 import**（环 ✗）⇒ 搬完依赖只剩一个方向 `host → core`。
import { section, scriptBodies, normalize, hasGeneratedMarker } from './lib/core/text.mjs';
import { hatchFiles } from './lib/host/hatches.mjs';
// 转出（老调用方不变 ✓）：自证与其它工具仍从 `editor/equiv.mjs` 取这几个名字。
export { section, scriptBodies, normalize };

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const COMPILER = 'editor/compile-story.mjs';

/** 纯函数：形式归一 —— 已搬到 `editor/lib/core/text.mjs`（本文件只转出，见顶部 import）。 */

/** **该不该拒绝"裸跑"**（`#794` 观察项 ✓）—— 纯谓词 ✓（所以自证能驱动它 ✓，无需夹具文件 ✓）。
 *  条件严格写成「**未显式给 `--hand`** ∧ 默认目标**带生成标记**」✓ ⇒ 两个**不误报**面：
 *   ① 显式给了 `--hand` ⇒ 照跑 ✓；② **未翻面**故事（默认目标就是手写源 ⇒ **无标记** ✓）⇒ 照跑 ✓。
 *  为什么必须拒绝 ✓（实测）：翻面后默认 `--hand` 指的是**产物**（带标记 ⇒ 只含 A 桶成员 ✓），
 *   而生成侧＝产物 **＋ 登记过的手写逃生舱文件** ⇒ 两侧**结构不同** ⇒ 拿一对必然不等的东西跑完，
 *   再报「手写 23 / 生成 25」✗ —— 看着像**数据错** ✗，其实与数据对错**无关** ✓（是**跑法**问题 ✓）。 */
export const bareHandRefusal = ({ handGiven = false, defaultExists = true, defaultText = '' } = {}) => {
	if (handGiven) return null;                       // 显式给了 ⇒ 照跑 ✓
	if (!defaultExists) return 'missing';             // 默认目标不存在 ⇒ **更不能沉默** ✗（实测：原来会无声地晚失败 ✗）
	if (hasGeneratedMarker(defaultText)) return 'product';
	return null;                                      // 未翻面（手写源 ⇒ 无标记）⇒ 照跑 ✓
};

const selftest = () => {
	let bad = 0;
	const t = (label, ok) => { if (!ok) bad++; console.log(`${ok ? '✓' : '✗'} 自证·${label}`); };
	// 实测到的假绿（审查提出）：字符串里的 `//` 曾被正则吃掉 ⇒ 两份不同的 URL 归一后相同
	t('反例：字符串里的 `//` 不许被当注释（`https://a/x` vs `https://b/y` ⇒ 归一后**不同**）',
		normalize("const u = 'https://a.example/x';") !== normalize("const u = 'https://b.example/y';"));
	t('边界：字符串里出现注释定界符也原样保留（`/* */` / `<!-- -->` / `/% %/`）',
		normalize("const a = '/* x */';") !== normalize("const a = '/* y */';"));
	t('正例：真注释与空白/冗余尾逗号被归一（`a:1, // c` vs `a:1` ⇒ 相同）',
		normalize('const o = { a: 1, // 注释\n};') === normalize('const o = { a: 1 };'));
	t('边界：数据面混进函数值 ⇒ walk 抓得到（"数据必须是数据"）',
		walk({ a: 1, b: () => 1 }).functions === 1 && walk({ a: 1 }).functions === 0);
	t('差异要说清**哪个成员／哪组实参**（不许只说"两版行为不同"）', (() => {
		const mk = (r) => ({ a: [[['x'], r]] });
		const d = diffContract(mk({ ok: '1' }), mk({ ok: '2' }));
		return d.n === 1 && d.text.includes('`a`') && d.text.includes('手写 1 / 生成 2');
	})());
	t('求值失败 ⇒ **干净判据**（不抛栈）：语法坏的输入返回 { err } 而不是异常', (() => {
		const r = evalSide('const x = ;', '测试侧');
		return !!r.err && !r.win && /求值失败/.test(r.err);
	})());
	t('边界：调用抛错也记录（两版行为不同看得出来）',
		call(() => { throw new Error('boom'); }, []).threw === 'boom' && call((x) => x, [1]).ok === '1');
	t('边界：没有已声明 id 时实参表仍非空（未知 id 探针恒在）',
		declaredIds({ Game: {} }).all.length === 0 && probeArgs(declaredIds({ Game: {} })).length >= 3);
	t('反例：**未给 `--hand`** ∧ 默认目标是产物（带生成标记）⇒ 拒绝 ✓',
		bareHandRefusal({ handGiven: false, defaultText: ':: Game Tables [script]\n// @generated by x\n…' }) === 'product');
	t('边界：**显式给了 `--hand`** ⇒ 照跑（不误报）✓',
		bareHandRefusal({ handGiven: true, defaultText: '// @generated by x\n…' }) === null);
	t('边界：**未翻面**故事（默认目标无标记）⇒ 照跑（不误报）✓',
		bareHandRefusal({ handGiven: false, defaultText: ':: Game Tables [script]\nconst A = 1;\n' }) === null);
	t('反例：**默认目标不存在** ⇒ 拒绝（不许无声晚失败 ✗）',
		bareHandRefusal({ handGiven: false, defaultExists: false }) === 'missing');
	if (bad) { console.error(`\n✗ 自证失败 ${bad} 项`); process.exit(1); }
	console.log('\n✔ 自证通过（12 例：裸跑拒绝（产物/不存在）2 例 ＋ 两个不误报面 2 例 ＋ 字符串里的注释定界符 3 例 · 函数值 1 例 · 异常 1 例 · 空 id 实参表 1 例）');
};

// ⚠️ **主模块守卫**（实测踩到）：这些脚本**同时是库**（`equiv` 被 `extract` 导入、`compile` 被 `equiv` 起子进程）。
// 没有守卫时，`import` 它们会**执行对端的 CLI**（实测：`node editor/extract-story.mjs --selftest` 打出的是
// `equiv` 的自证然后退出 ⇒ 自己的自证根本没跑）。守卫＝「只在被当脚本执行时才跑 CLI」。
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
if (isMain && process.argv.includes('--selftest')) { selftest(); process.exit(0); }

const main = () => {
	const slug = process.argv[2];
	if (!slug) { console.error('用法：node editor/equiv.mjs <slug> [--rules] [--l3=hard|report] [--hand=…] [--gen=…]'); process.exit(2); }
	const argOf = (name, dflt) => { const h = process.argv.find((a) => a.startsWith(`--${name}=`)); return h ? h.slice(name.length + 3) : dflt; };
	const rulesMode = process.argv.includes('--rules');
	const l3Mode = argOf('l3', 'hard');
	if (!L3_MODES.includes(l3Mode)) { console.error(`✗ --l3 只接受 ${L3_MODES.join('|')}（实得 ${l3Mode}）`); process.exit(2); }
	const handGiven = process.argv.some((a) => a.startsWith('--hand='));
	const defaultTwee = rulesMode ? '17-rules.twee' : '15-tables.twee';
	const handPath = join(ROOT, argOf('hand', `stories/${slug}/${defaultTwee}`));
	// `#794` 观察项：**裸跑（未显式给 `--hand`）＋ 默认目标是产物 ⇒ 当场拒绝并指路** ✓（见 `bareHandRefusal` ✓）。
	// ⚠️ 放在**昂贵比较之前** ✓（复核口径 ✓）：下面要连编译两次 ＋ 逐字节比 ⇒ 跑完再报等于让人白等 ✓。
	const defaultExists = existsSync(handPath);
	const refusal = bareHandRefusal({ handGiven, defaultExists, defaultText: defaultExists ? readFileSync(handPath, 'utf8') : '' });
	if (refusal) {
		const base = `stories/${slug}/gates/equiv-baseline/${defaultTwee}.txt`;
		const rel = `stories/${slug}/${defaultTwee}`;
		if (refusal === 'product') {
			const hint = existsSync(join(ROOT, base))
				? `\n   ⇒ 建议：\`--hand=${base}\`（冻结基线 ✓）`
				: `\n   该模式暂无冻结基线（\`${base}\` 不存在）⇒ 需**先落基线**（带票号/理由 ✓）或显式给 \`--hand=<手写契约路径>\``;
			console.error(`✗ 未显式给 --hand，而默认目标 \`${rel}\` 是**产物**（带生成标记）：\n`
				+ `  产物只含 A 桶成员，而本工具要比的是**整份契约**（生成侧还会并入登记过的手写逃生舱文件）\n`
				+ `  ⇒ 两侧**结构不同**、必然不等 —— 这是**跑法**问题，不是数据问题。${hint}`);
		} else {
			console.error(`✗ 未显式给 --hand，而默认目标 \`${rel}\` **根本不存在**：\n`
				+ `  该模式在本故事里没有可判的源 ⇒ 既不点名不存在的路径、也不静默晚失败 ✗\n`
				+ `  ⇒ 需**先落基线**（\`${base}\`，带票号/理由 ✓）或显式给 \`--hand=<手写契约路径>\``);
		}
		process.exit(2);
	}
	const hand = readFileSync(handPath, 'utf8');

	// ── 自跑编译器两次 ⇒ 幂等 ＋ 拿到产物（不判陈旧件） ──
	const genDir = join(ROOT, 'build/generated', slug);
	const idemDir = join(ROOT, 'build/generated', `.idem-${slug}`);
	runNode([COMPILER, slug, `--out=${genDir}`], { cwd: ROOT });
	runNode([COMPILER, slug, `--out=${idemDir}`], { cwd: ROOT });
	const names = [...new Set([...readdirSync(genDir), ...readdirSync(idemDir)])].sort();
	const idemOk = names.length > 0 && names.every((n) => readFileSync(join(genDir, n)).equals(readFileSync(join(idemDir, n))));
	const gen0 = readFileSync(join(genDir, rulesMode ? '17-rules.twee' : '15-tables.twee'), 'utf8');
	// **产物侧 ＝ 生成物 ＋ 登记过的手写逃生舱文件**（`#787` 翻面形状）：非 A 桶成员装不进生成物 ⇒ 它们住手写件，
	// 而行为门要比的是**整份契约**；手写侧（冻结基线）本来就含它们 ⇒ 只比生成物会得到"少了成员"的**假差** ✗。
	// 单一真源＝`editor/escape-hatch.json` 的 `hatchFiles` ✓ —— 读它**共用** `lib/host/hatches.mjs` 的实现 ✓
	//（本文件原来有一份**内联复制** ✗，已收掉 ✓ —— 避免两个消费者各写一份 ✓）。
	const gen = [gen0, ...hatchFiles(slug).map((f) => readFileSync(f, 'utf8'))].join('\n');

	const results = [[idemOk, `幂等：连编译两次产物逐字节相同（${names.length} 份：${names.join('、')}）`]];
	const l3Line = (nh, ng, what) => {
		const same = nh === ng;
		const at = [...nh].findIndex((c, i) => c !== ng[i]);
		return [same || l3Mode === 'report',
			`L3 形式等价（--l3=${l3Mode}）：${what}（手写 ${nh.length}B / 生成 ${ng.length}B）${same ? '' : `\n    首个差异 @${at}\n    手写 …${nh.slice(Math.max(0, at - 40), at + 60)}\n    生成 …${ng.slice(Math.max(0, at - 40), at + 60)}`}`];
	};

	if (rulesMode) {
		// ── 条件表：L1 = 两版各自求值后**行数组深度相等**（＝列级一致：少抽一个字段也会不等） ──
		const rowsOf = (text) => { const box = sandboxOf(); vm.runInContext(scriptBodies(text).join('\n'), box, { timeout: 5000 }); return box.Sg.story.rules(); };
		const hr = rowsOf(hand), gr = rowsOf(gen);
		/** 字段直方图：把"抽了哪些列"显式打出来（`#557` 那条老账：总体非空拦不住少抽一项）。 */
		const hist = (rows) => {
			const h = {};
			for (const r of rows) for (const k of Object.keys(r)) h[k] = (h[k] ?? 0) + 1;
			return Object.fromEntries(Object.entries(h).sort(([a], [b]) => (a < b ? -1 : 1)));
		};
		const hh = hist(hr), gh = hist(gr);
		results.push([JSON.stringify(hr) === JSON.stringify(gr),
			`L1 条件表**深度相等**（手写 ${hr.length} 行 / 生成 ${gr.length} 行）${JSON.stringify(hr) === JSON.stringify(gr) ? '' : '\n    两版不同（见下条字段直方图与 L3 定位）'}`]);
		results.push([JSON.stringify(hh) === JSON.stringify(gh),
			`L1 字段直方图一致（每列出现多少次）：${Object.entries(hh).map(([k, v]) => `${k} ${v}`).join(' · ')}`]);
		results.push(l3Line(normalize(section(hand, 'StoryRules') ?? ''), normalize(section(gen, 'StoryRules') ?? ''), '剥注释/空白/冗余尾逗号后逐字节相同'));
		results.push([hr.length > 0 && Object.keys(hh).length > 0, `判到的面不为空：条件表 ${hr.length} 行 · ${Object.keys(hh).length} 列`]);
	} else {
		// ── 表 ＋ 契约（P0 原口径） ──
		const H = evalSide(scriptBodies(hand).join('\n'), '手写侧（基线）');
		const G = evalSide(scriptBodies(gen).join('\n'), '生成侧（产物）');
		if (!H.win || !G.win) {
			results.push([false, `两侧求值（判据的红要讲人话 ✓）：${[H.err, G.err].filter(Boolean).join('；')}`]);
		}
		const hWin = H.win, gWin = G.win;
		const hs = hWin ? snapshot(hWin) : null, gs = gWin ? snapshot(gWin) : null;
		// 段数只**报告**（生成物的段划分与手写不要求同形：`Cave Declarations` 那类"局部常量段"会并进契约的 `const`）；
		// 真正要判的是**契约成员的键集合**（下面那条）＋ 行为。
		console.log(`  · 段数（只报告）：手写 ${scriptBodies(hand).length} 段 / 生成 ${scriptBodies(gen).length} 段`);
		if (hs && gs) {
			const hk = Object.keys(hs.contract).sort(), gk = Object.keys(gs.contract).sort();
			const onlyHand = hk.filter((k) => !gk.includes(k)), onlyGen = gk.filter((k) => !hk.includes(k));
			results.push([onlyHand.length === 0 && onlyGen.length === 0,
				`L1 契约**键集合**一致（手写 ${hk.length} / 生成 ${gk.length}）${onlyHand.length ? `\n    仅手写有：${onlyHand.join('、')}` : ''}${onlyGen.length ? `\n    仅生成有：${onlyGen.join('、')}` : ''}`]);
			results.push([hs.game === gs.game, `L1 数据容器深度相等（含 State/Notes/Consequences；**对象键序不计**，数组序仍判）${hs.game === gs.game ? '' : `\n    手写 ${String(hs.game).slice(0, 220)}\n    生成 ${String(gs.game).slice(0, 220)}`}`]);
			// 判**行为**，不判**顺序**：成员在源里的先后不是语义（曾因"生成物把某成员排到末尾"而假红 ✗）
			const cd = diffContract(hs.contract, gs.contract);
			results.push([Object.keys(hs.contract).length > 0 && cd.n === 0,
				`L1 契约**多实参**行为相等（${Object.keys(hs.contract).length} 个成员 × ${probeArgs(hs.ids).length} 组实参）${cd.n ? `\n    ${cd.text}` : ''}`]);
			results.push(l3Line(scriptBodies(hand).map(normalize).join('|'), scriptBodies(gen).map(normalize).join('|'), '词法遮蔽注释 ＋ 去空白/冗余尾逗号后逐字节相同'));
			results.push([hs.walk.functions === 0 && gs.walk.functions === 0, `数据面是数据：容器内函数值 0 个（手写 ${hs.walk.functions} / 生成 ${gs.walk.functions}）`]);
			const surface = { '容器键数': Object.keys(JSON.parse(hs.game === 'null' ? '{}' : hs.game)).length, '数据叶子数': hs.walk.leaves, '契约成员数': Object.keys(hs.contract).length, '探针调用次数': hs.probes, '归一字节数': scriptBodies(hand).map(normalize).join('|').length };
			const empty = Object.entries(surface).filter(([, v]) => !v).map(([k]) => k);
			results.push([empty.length === 0, `判到的面不为空：${Object.entries(surface).map(([k, v]) => `${k} ${v}`).join(' · ')}${empty.length ? `　✗ 为 0 的：${empty.join('、')}` : ''}`]);
		}
	}

	let bad = 0;
	for (const [ok, msg] of results) { console.log(`${ok ? '✓' : '✗'} ${msg}`); if (!ok) bad++; }
	console.log(bad ? `\n✗ 等价判据未通过（${bad} 项）` : `\n✔ ${slug}${rulesMode ? '（条件表）' : ''}：手写版 ↔ 数据版 等价（幂等 ＋ L1 ＋ L3(--l3=${l3Mode}) ＋ 面非空）`);
	process.exit(bad ? 1 : 0);
};

if (isMain) main();
