// K4 门（`#762` 车道 C）：**生成物标记 · 产物新鲜度 · 逃生舱可枚举**
//
// 为什么需要它（设计稿 §3 的 K4 判据）：D2 把 twee 定为**产物**（源是 `stories/<slug>/data/`），
//   "产物"这个身份必须**机械可判**，否则它只是注释里的一句话：
//     ① **标记**：每个生成物首部必须有 `@generated`（谁生成、源在哪）；
//     ② **新鲜度**：拿 `data/` 重编一次，产物必须**逐字节相同**（＝"带标记的文档只是投影"这条主张的实证）；
//        手改产物 = 下次编译被覆盖 ⇒ 这条会红；
//     ③ **逃生舱可枚举**：契约分类器（`editor/classify-contract.mjs`）判为 **C 桶**（含任意逻辑）的成员，
//        必须在 `editor/escape-hatch.json` 里**逐条登记**（理由 ＋ 票号）；**清单外出现即红**、
//        **清单里腐烂（已不是 C 桶）也红** ⇒ 例外是"可枚举的"，不是"随手加的"。
//
// 口径（避免假红／假绿）：
//   · 本门**自己跑编译器**（不读工作区里可能陈旧的 `build/generated/`）⇒ 判的永远是"现在能不能重编出来"；
//   · 只对**有 `data/` 的故事**判（没有 data 的故事＝还没数据化 ⇒ ①/② 跳过，不假装判过）；
//   · 分类器把"形状能看懂、但现有 kind 缺字段"判成 **B**（需声明式扩展）⇒ **不是**逃生舱；
//     只有"含任意逻辑、要么下沉引擎要么登记"的才是 **C** ✓。
//
// 用法：node editor/k4.mjs [--selfcheck]（用 `--selfcheck` 而不是 `--selftest`：见下方守卫说明）
//
// `#794` 第 4 条（本文件）：**命令体已抽到 `editor/lib/host/commands.mjs` 的 `k4Command`** ✓
//   ⇒ 本壳只做三件：**转出**判据（纯函数住在 `lib/core/k4criteria.mjs` ✓）· 跑自证 · 转发 argv。
//   ⇒ 与 `cli.mjs k4` **共用同一具身体** ✓（不是两份实现 ✗）—— 等价性按构造成立 ✓。
import { fileURLToPath } from 'node:url';
import { MARKER, markerProblems, freshnessProblems, escapeHatchProblems, contractSourceText, staleTrackedProblems } from './lib/core/k4criteria.mjs';
import { hasGeneratedMarker } from './lib/core/text.mjs';
import { k4Command } from './lib/host/commands.mjs';
import { exitWithRc } from './lib/host/proc.mjs';
export { MARKER, hasGeneratedMarker, markerProblems, freshnessProblems, escapeHatchProblems, contractSourceText, staleTrackedProblems };

// ⚠️ **主模块守卫**（实测踩到）：本文件**同时是库**（判据函数被测试／下游当纯函数 import ✓）。
//   没有守卫时，`import` 它会**跑完整门**（0.22s ＋ 1592B 输出 ✗），且门红时 `process.exit(1)` 会**劫持导入方** ✗。
//   守卫＝「只在被当脚本执行时才跑 CLI」✓；`isMain` 的声明必须在 **imports 之后、逻辑之前** ✓ ——
//   放后面会 TDZ ✗（`Cannot access 'isMain' before initialization`，实测踩过）。
const isMain = process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1];
// ⚠️ **自证旗标用 `--selfcheck` 而不是 `--selftest`**：这是**防御性**设计，不是绕路 ——
//   起因是一次真事故（`#794`）：当时存在"`<某门> --selftest` 被 import 的模块劫持"这个缺口
//   （被测模块的 `--selftest` 派发当时**没有 isMain 守卫** ⇒ import 它会跑自己的自证并 `process.exit`）。
//   **该缺口后来已修**：`compile-story.mjs` 在 `#769`、`classify-contract.mjs` 在 `#772` 里也守住了。
//   ⇒ 本门**仍保留独立旗标**：多一层防御不吃亏，且将来任一门再犯这族错时，本门不会被带塌 ✓。
if (isMain && process.argv.includes('--selfcheck')) {
	let bad = 0;
	const cases = [
		['正例①：生成物带标记 ⇒ 不报', markerProblems([{ path: 'a', text: `:: X [script]\n// ${MARKER} by y（源：z）` }]).length === 0],
		['🔴 反例①：生成物没标记 ⇒ 报', markerProblems([{ path: 'a', text: ':: X [script]' }]).length === 1],
		['正例②：两次编译逐字节相同 ⇒ 不报', freshnessProblems({ a: 'x' }, { a: 'x' }).length === 0],
		['🔴 反例②：两次不同 ⇒ 报（不幂等 ⇒ 手改会被覆盖/工作区常脏）', freshnessProblems({ a: 'x' }, { a: 'y' }).length === 1],
		['正例③：C 桶已登记且带理由票号 ⇒ 不报', escapeHatchProblems([{ name: 'lootText', bucket: 'C' }], { hatches: [{ member: 'lootText', reason: 'r', ticket: '#736' }] }).length === 0],
		['🔴 反例③：C 桶没登记 ⇒ 报（清单外出现）', escapeHatchProblems([{ name: 'x', bucket: 'C' }], { hatches: [] }).length === 1],
		['🔴 反例③：登记腐烂（已不是 C 桶）⇒ 报（清单要收缩）', escapeHatchProblems([{ name: 'x', bucket: 'A' }], { hatches: [{ member: 'x', reason: 'r', ticket: '#1' }] }).length === 1],
		['🔴 反例③：登记缺理由/票号 ⇒ 报', escapeHatchProblems([{ name: 'x', bucket: 'C' }], { hatches: [{ member: 'x' }] }).length === 1],
		['边界③：B 桶（需声明式扩展）**不算**逃生舱 ⇒ 不报', escapeHatchProblems([{ name: 'x', bucket: 'B' }], { hatches: [] }).length === 0],
		['边界③：登记表按**故事**过滤（别的故事的登记不算腐烂）', escapeHatchProblems([{ name: 'x', bucket: 'A' }], { hatches: [{ member: 'x', slug: 'other', reason: 'r', ticket: '#1' }] }, 'mine').length === 0],
		['边界③前置：手写契约源**排除产物**（带 `@generated` 的 twee 不算源）', contractSourceText([['a.twee', ':: X\n// @generated by y'], ['b.twee', ':: Y'], ['c.json', '{}']]).handCount === 1],
		['🔴 反例③前置：**行内**提到 `@generated`（不在行首）⇒ **仍算手写源**（锚定：锚定错了会把逃生舱文件整个排除 ⇒ 门假红）', contractSourceText([['a.twee', ':: X [script]\n// 本文件不带 @generated ⇒ 它是手写件\nObject.assign({}, {})']]).handCount === 1],
		['边界③前置：全是产物 ⇒ 手写源为空（C 桶结构性为 0，不静默）', contractSourceText([['a.twee', '// @generated']]).handCount === 0],
		['边界③前置：非 `.twee` 文件不计入手写源', contractSourceText([['d.md', 'hello']]).handCount === 0],
		['正例④：带标记的 tracked 文件与产物**逐字节相同** ⇒ 不报', staleTrackedProblems([['stories/s/15-tables.twee', 'x\n// @generated by c']], { '15-tables.twee': 'x\n// @generated by c' }).problems.length === 0],
		['🔴 反例④：带标记但**与重编产物不一致** ⇒ 报（两处真相）', staleTrackedProblems([['stories/s/15-tables.twee', 'x\n// @generated']], { '15-tables.twee': 'y\n// @generated' }).problems.length === 1],
		['🔴 反例④：带标记却**没有同名产物** ⇒ 报（来源已断）', staleTrackedProblems([['stories/s/15-tables.twee', '// @generated']], { '其它.twee': 'x' }).problems.length === 1],
		['边界④：**不带标记**的手写文件 ⇒ 不报（天然棘轮：手写故事零影响）', staleTrackedProblems([['stories/s/15-tables.twee', '手写']], { '15-tables.twee': '别的' }).problems.length === 0],
		['边界④：非 `.twee`（如产物 `audit.json`）⇒ 不报（本判据只管编译器产出的 twee）', staleTrackedProblems([['stories/s/audit.json', '// @generated']], {}).problems.length === 0],
		// `#842`：**模板串里的"行首 //"不算标记** ✓ —— 经由**判据**断言（不直接引谓词 ⇒ 与本仓两处实现的名字解耦 ✓，也更贴"理由" ✓）
		['🔴 反例·**模板串里**的一行以 `// @generated` 开头 ⇒ **不算**标记（旧版把它当产物 ⇒ 报"来源已断" ✗）', staleTrackedProblems([['stories/s/15-tables.twee', 'const t = `\n// @generated\n`;']], {}).problems.length === 0],
		['正例·同一文件里**另有真标记** ⇒ 仍算（遮模板串不吃掉真注释 ✓）', (() => { const r = staleTrackedProblems([['stories/s/15-tables.twee', 'const t = `\n// @generated\n`;\n// @generated by x']], { '15-tables.twee': 'const t = `\n// @generated\n`;\n// @generated by x' }); return r.marks === 1 && r.problems.length === 0; })()],
	];
	for (const [label, cond] of cases) { if (cond) console.log(`  ✓ 自证·${label}`); else { bad++; console.error(`  ✗ 自证·${label}`); } }
	if (bad) { console.error(`\n✗ 自证未通过（${bad} 项）`); process.exit(1); }
	console.log('\n✔ 自证通过（19 条：标记 2 ＋ 新鲜度 2 ＋ 逃生舱双向 5 ＋ 手写源口径 3 ＋ 生成物不许独改 5 ＋ 模板串口径 2）');
	process.exit(0);
}

/** `#794`：命令体已抽成**共享函数**（`lib/host/commands.mjs` 的 `k4Command` ✓）——
 *  本壳只负责"转发自己的 argv ＋ 用自己的程序名渲染用法行" ✓。 */
const main = () => {
	// 入口统一走 `exitWithRc` ✓（house style：rc 非 number 当场抛 ⇒ 命令体返回值的错误当场可见 ✓）
	exitWithRc(k4Command(process.argv.slice(2), { prog: 'node editor/k4.mjs', sub: '' }));
};

if (isMain) main();
