// `#1185`：**生成物家族的"产物必有源"守卫**。
//
// 来源：评审 `#1183`（B4）时的非阻断发现之二 —— 数据源被删而生成产物仍在位时，构建与相关门都不红，
// 残留产物会被继续打进包，读者以为源还在。
//
// 判据：家族里每个生成物都带着 `@generated` 标记（那行写着"源：…"）。逐件核对该源**是否还在**；
// 源删而产物在 → 大声报并**点名两侧**（产物路径 ＋ 它声称的源）。
//
// 家族谓词与标记解析都取**单一权威**（本模块导出，别处引用，不各写一份）：
// · 家族＝`stories/<slug>/1[5678]-*.twee`（15／16／17／18）＋ `stories/<slug>/00-meta.twee`；
// · 标记＝`// @generated by …（源：<路径>）`，与 `scripts/audit/gates/literals.mjs` 的
// `deriveDataSections` 同一条正则口径（那里判"源是否在同故事 data/ 下"，这里判"源是否还在"）。

/** 生成物家族谓词（单一权威）。 */
export const isGeneratedFamily = (path) =>
	/^stories\/[^/]+\/1[5678]-[^/]*\.twee$/.test(String(path)) || /^stories\/[^/]+\/00-meta\.twee$/.test(String(path));

/** 从生成物的 `@generated` 标记里取它声称的源路径（无标记 → null）。与 literals 门同一条正则。 */
export const declaredSourceOf = (text) => {
	const m = /@generated by [^(（]*[（(]源[：:]\s*([^)）]+)[）)]/.exec(String(text ?? ''));
	return m ? m[1].trim() : null;
};

/** `#1350` 片 3：**多来源**（`#1324` 之后的产物可能有两个源：`rules.json` ＋ `passages.json`）⇒ 拆开逐条核。
 * ★ 口径：**任一声明的源存在即可**（✗ 不再只取第一个 ⇒ 否则第二来源被忽略 ⇒ 误报"源不在磁盘上" ✗）。 */
export const declaredSourcesOf = (text) => {
	const one = declaredSourceOf(text);
	if (!one) return [];
	return one.split(/\s*＋\s*/).map((x) => x.trim()).filter(Boolean);
};

/**
 * 纯函数：生成物家族两向核对。
 * `files` 是 `{ 路径: 全文}`（调用方过滤后传入，或全量由本函数按家族谓词筛）；
 * `exists` 注入"该路径在磁盘上是否存在"；`listed`（可选）注入"该路径是否在某故事的清单里"。
 * 返回 `[{ path, code, why}]`：
 * · `source-missing` —— 标记载明的源不在磁盘上（源删而产物残留）；
 * · `no-marker` —— 家族成员没有 `@generated` 标记（看不出源，也就无从核源）。
 */
export const generatedFamilyProblems = ({ files = {}, exists }) => {
	const out = [];
	for (const [path, text] of Object.entries(files ?? {})) {
		if (!isGeneratedFamily(path)) continue;
		const srcs = declaredSourcesOf(text);
		const src = srcs[0] ?? null;
		if (!srcs.length) {
			out.push({ path, code: 'no-marker', why: `生成物家族成员没有 \`@generated\` 标记（看不出源 ⇒ 无从核源）` });
			continue;
		}
		// `#1350` 片 3：**任一声明的源存在即可**（多来源产物的正确口径 ✓）
		if (!srcs.some((x) => exists(x))) {
			out.push({ path, code: 'source-missing', why: `产物仍在，但它标记载明的源「${srcs.join(' ＋ ')}」**都不在**磁盘上（源被删而产物残留）` });
		}
	}
	return out;
};
