// `#1185`：**生成物家族的"产物必有源"守卫**。
//
// 来源：评审 `#1183`（B4）时的非阻断发现之二 —— 数据源被删而生成产物仍在位时，构建与相关门都不红，
// 残留产物会被继续打进包，读者以为源还在。
//
// 判据：家族里每个生成物都带着 `@generated` 标记（那行写着"源：…"）。逐件核对该源**是否还在**；
// 源删而产物在 → 大声报并**点名两侧**（产物路径 ＋ 它声称的源）。
//
// 家族谓词与标记解析都取**单一权威**（本模块导出，别处引用，不各写一份）：
// · 家族＝`stories/<slug>/<两位前缀>-*.twee`（★前缀集见 `GENERATED_PREFIXES`：00／15／16／17／18／19 —— `#1588` 后）；
// · 标记＝`// @generated by …（源：<路径>）`，与 `scripts/audit/gates/literals.mjs` 的
// `deriveDataSections` 同一条正则口径（那里判"源是否在同故事 data/ 下"，这里判"源是否还在"）。

/**
 * ★★ `#1588`：生成物家族的**两位前缀集**（**单一权威**）。
 * ★**为什么是"前缀集"而不是又一条正则**：★原正则写死 `1[5678]` ⇒ `#1585` 新加的 `19-events.twee` **不在家族里**
 *   ⇒ 它被当**源件**（`dist-fresh` 口径错）／删了也**不触发重编**（靠 `missing-manifest` 兜底才红）✗。
 * ★**名单的来源**：★`EMITTED_PREFIXES` ＝ `emit.mjs` 字面写出的键（`00-meta`／`15-tables`／`17-rules`／`18-chargen`／`19-events`）
 *   ⇒ ★由判据件 `test/generated-family.mjs` 从生成器**源面抽键**钉住（✗ 靠人眼同步 ✓）；
 *   ★`CONVENTION_PREFIXES` ＝ 名字由数据给的那一类（`16-notes-*`）✓。
 * ★**加新产物 ⇒ 在这里登记 ＋ 判据件会告诉你漏了**（照 `VOCAB.prefixes` 的镜像 ＋ 钉法惯例 ✓）。
 */
// ★★ `#1588`：★**两侧分开**（实测口径 —— ✗ 混成一份会说不清"谁是真权威"）：
//   · **生成器字面写出的**（`emit.mjs` 里 `files['xx-…'] = …`）⇒ ★可由判据件**钉**（跑源面抽键 ✓）；
//   · **约定前缀**：`16-notes-*.twee` 的名字**由数据给**（`data/notes.json` 的块 `file` 字段 ⇒ 见 `emit.mjs`
//     的 `notesFace` 支）⇒ ★生成器**不字面写** `16-` ⇒ 只能按**约定**登记（本条即该约定的落点 ✓）。
export const EMITTED_PREFIXES = Object.freeze(['00', '15', '17', '18', '19']);
/** ★**约定**前缀（名字由数据给）：`16-notes-*.twee`（notes 面；`#215`）✓ */
export const CONVENTION_PREFIXES = Object.freeze(['16']);
/** 家族前缀集（＝上面两侧之并，`isGeneratedFamily` 用它 ✓）。 */
export const GENERATED_PREFIXES = Object.freeze([...EMITTED_PREFIXES, ...CONVENTION_PREFIXES].sort());

/** 生成物家族谓词（单一权威）。★`#1588`：★从 `GENERATED_PREFIXES` **派生**（✗ 再写一条正则 ⇒ 又会漏下一个）。 */
export const isGeneratedFamily = (path) => {
	const m = /^stories\/[^/]+\/([0-9]{2})-[^/]*\.twee$/.exec(String(path));
	return !!m && GENERATED_PREFIXES.includes(m[1]);
};

/** 从生成物的 `@generated` 标记里取它声称的源路径（无标记 → null）。与 literals 门同一条正则。 */
export const declaredSourceOf = (text) => {
	const m = /@generated by [^(（]*[（(]源[：:]\s*([^)）]+)[）)]/.exec(String(text ?? ''));
	return m ? m[1].trim() : null;
};

/** `#1350` 片 3：**多来源**（`#1324` 之后的产物可能有两个源：`rules.json` ＋ `passages.json`）⇒ 拆开逐条核。
 * ★ 口径：**任一声明的源存在即可**（✗ 不再只取第一个 ⇒ 否则第二来源被忽略 ⇒ 误报"源不在磁盘上" ✗）。 */
export const declaredSourcesOf = (text) => {
	const one = declaredSourceOf(text);
	if (!one) return [];
	return one.split(/\s*＋\s*/).map((x) => x.trim()).filter(Boolean);
};

/**
 * 纯函数：生成物家族两向核对。
 * `files` 是 `{ 路径: 全文}`（调用方过滤后传入，或全量由本函数按家族谓词筛）；
 * `exists` 注入"该路径在磁盘上是否存在"；`listed`（可选）注入"该路径是否在某故事的清单里"。
 * 返回 `[{ path, code, why}]`：
 * · `source-missing` —— 标记载明的源不在磁盘上（源删而产物残留）；
 * · `no-marker` —— 家族成员没有 `@generated` 标记（看不出源，也就无从核源）。
 */
export const generatedFamilyProblems = ({ files = {}, exists }) => {
	const out = [];
	for (const [path, text] of Object.entries(files ?? {})) {
		if (!isGeneratedFamily(path)) continue;
		const srcs = declaredSourcesOf(text);
		const src = srcs[0] ?? null;
		if (!srcs.length) {
			out.push({ path, code: 'no-marker', why: `生成物家族成员没有 \`@generated\` 标记（看不出源 ⇒ 无从核源）` });
			continue;
		}
		// `#1350` 片 3：**任一声明的源存在即可**（多来源产物的正确口径 ✓）
		if (!srcs.some((x) => exists(x))) {
			out.push({ path, code: 'source-missing', why: `产物仍在，但它标记载明的源「${srcs.join(' ＋ ')}」**都不在**磁盘上（源被删而产物残留）` });
		}
	}
	return out;
};
